[mypy]
python_version = 3.13
cache_dir = /tmp/.mypy_cache_arxiv_paper_evaluator
show_error_codes = True
pretty = True

[mypy-arxiv]
ignore_missing_imports = True

[mypy-arxiv.*]
ignore_missing_imports = True
